spring.application.name=fleetops
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/fleetops
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

